---
- name: Gather universal system information
  hosts: 192.168.122.236
  become: true
  tasks:
    - name: Update /tmp/hello_world.txt
      command: echo "$(date) - Hello World!" >> /tmp/hello_world.txt
    - name: Display resolv.conf contents
      command: cat resolv.conf chdir=/etc
      register: command_output
    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"
    - name: Print hello message
      debug:
        msg: "Hello from AWX!"
    - name: Simple debug test
      debug:
        msg: "Hello from AWX debug!"
    - name: Show OS and kernel info
      debug:
        msg: |
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
    - name: Show CPU information
      debug:
        msg: |
          CPUs: {{ ansible_processor_count }} physical x {{ ansible_processor_cores }} cores each
          CPU Model: {{ ansible_processor[-1] }}
    - name: Show memory information
      debug:
        msg: |
          Total RAM: {{ (ansible_memtotal_mb / 1024) | round(2) }} GB
    - name: Show disk usage (root mount)
      debug:
        msg: |
          Root FS Total: {{ (ansible_mounts[0].size_total / 1024**3) | int }} GB
          Root FS Available: {{ (ansible_mounts[0].size_available / 1024**3) | int }} GB
    - name: Show network information
      debug:
        msg: |
          Hostname: {{ ansible_fqdn }}
          Primary IP: {{ ansible_default_ipv4.address }}
          Interfaces: {{ ansible_interfaces | difference(['lo']) | join(', ') }}
    - name: Show package manager
      debug:
        msg: "Package Manager: {{ ansible_pkg_mgr }}"
    - name: Show system uptime
      command: uptime -p
      register: uptime_result
    - name: Display uptime
      debug:
        msg: "Uptime: {{ uptime_result.stdout }}"
