---
- name: Gather universal system information
  hosts: 192.168.122.236
  become: false
  gather_facts: true

  tasks:

    - name: Simple debug test
      debug:
        msg: "Hello from AWX debug!"
        verbosity: 0

    - name: Show OS and kernel info
      debug:
        msg: |
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
        verbosity: 0

    - name: Show CPU information
      debug:
        msg: |
          CPUs: {{ ansible_processor_count }} physical x {{ ansible_processor_cores }} cores each
          CPU Model: {{ ansible_processor[-1] }}
        verbosity: 0

    - name: Show memory information
      debug:
        msg: |
          Total RAM: {{ (ansible_memtotal_mb / 1024) | round(2) }} GB
          Available RAM: {{ (ansible_memory_mb.real.available / 1024) | round(2) }} GB
        verbosity: 0

    - name: Show disk usage (root mount)
      debug:
        msg: |
          Root FS Total: {{ (ansible_mounts[0].size_total / 1024**3) | int }} GB
          Root FS Available: {{ (ansible_mounts[0].size_available / 1024**3) | int }} GB
        verbosity: 0

    - name: Show network information
      debug:
        msg: |
          Hostname: {{ ansible_fqdn }}
          Primary IP: {{ ansible_default_ipv4.address }}
          Interfaces: {{ ansible_interfaces | difference(['lo']) | join(', ') }}
        verbosity: 0

    - name: Show package manager
      debug:
        msg: "Package Manager: {{ ansible_pkg_mgr }}"
        verbosity: 0

    - name: Show system uptime
      command: uptime -p
      register: uptime_result

    - name: Display uptime
      debug:
        msg: "Uptime: {{ uptime_result.stdout }}"
        verbosity: 0

    - name: Dump all gathered facts (may be very verbose)
      debug:
        var: ansible_facts
        verbosity: 0
